### PR TITLE
Added ru_ru.json

### PR DESCRIPTION
**Pull request by Felix14-v2**
- Each setting and its translation has been tested ingame
- ModMenu translations included

### CODE REVIEW

**Comment by FlorianMichael** [comment]
Thanks, but leave out the ModMenu translations, I find that better when the main description is only in English

**Comment by Felix14-v2** [comment]
As you wish! Should I leave summary translated?

**Comment by FlorianMichael** [comment]
No, just remove the two ModMenu translations, it's a really cool idea, but I don't want Russians to think that the mod is Russian.

**Comment by Felix14-v2** [comment]
> I don't want Russians to think that the mod is Russian.

If this is the reason, then you can be calm — there has never been a problem with this. We have never had segregation by country, and the russian text in mods is always perceived solely as a translation. ModMenu displays the author and links in the description section, so if someone is interested, he can easily recognize country by them. In addition, translating the description in ModMenu helps modpack users when they don't know in advance what reach mod is responsible for.

**Comment by FlorianMichael** [comment]
Right again, actually you are already right, thank you very much

**Pull request merged**
